%% input parameter
clear
clc
addpath ../FEM_toolbox/2d
ebc_left = 0; 
ebc_right = 1;
x_left = -1;
x_right = 0;
file = "data/demo.m"; % the mesh file generated by Gmsh
%% set geometry & mesh
run(file)
t = msh.TRIANGLES(:, 1:3);  % the connectivity
P = msh.POS(:,1:2); % the position
numNodes = size(P,1);
EBCvec = construct_EBCvec(P, x_left, x_right, ebc_left, ebc_right);
%% solve for u
K = fast_assemble(P, t, 'G');  % the important matrix Q R
F = zeros(numNodes, 1);
[Kmod, Fmod] = apply_EBC(K, F, EBCvec);
u = Kmod \ Fmod;
trisurf(t, P(:,1), P(:,2), u);
axis equal

%% plot gradient of result
[uxx, uyy] = get_gradu(P, t, u);
p1 = P(t(:,1),:);
p2 = P(t(:,2),:);
p3 = P(t(:,3),:);
p_center = (p1+p2+p3)/3;
% scatter(p_center(:,1), p_center(:,2), 60, uxx');
quiver(p_center(:,1), p_center(:,2), uxx, uyy);
axis equal
