clear;clc;
% addpath ..
file = "hollow_sphere/hollow_sphere.m"; % the mesh file generated by Gmsh
run(file)
t = msh.TETS(:, 1:4);  % the connectivity
P = msh.POS(:,1:3); % the position
% profile on
u = run_laplace3d(P, t, "left");
trisurf(t, P(:,1), P(:,2), P(:,3),u);
axis equal
